name: x86_64

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dart-x86_64:
    runs-on: "ubuntu-latest"
    container:
      image:
        dart
      options: --tty --platform linux/amd64
    steps:
      - uses: actions/checkout@v3
      - name: Compute BUILD_VERSION
        run: echo "BUILD_VERSION=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Show BUILD_VERSION
        run: echo "BUILD_VERSION=${{ env.BUILD_VERSION }}"

      - name: Show Dart SDK version
        run: echo "Dart SDK version `dart --version`"

      - name: List files
        run: pwd && ls -la

      - name: Git status
        run: git status

      - name: Git log
        run: git log -n 1
