name: aarch64

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dart-aarch64:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Compute BUILD_VERSION
        run: echo "BUILD_VERSION=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Show environment
        run: |
          echo "USER=${USER}"
          echo "UID=${UID}"
          echo "GID=${GID}"
          echo ID_U=`id -u`
          echo ID_G=`id -g`
          echo "RUNNER_UID=`id -u`" >> $GITHUB_ENV
          echo "RUNNER_GID=`id -g`" >> $GITHUB_ENV

      - uses: uraimo/run-on-arch-action@v2
        name: Run Dart on aarch64
        with:
          arch: aarch64
          distro: ubuntu18.04
          setup: |
            curl --connect-timeout 15 --retry 5 "https://storage.googleapis.com/dart-archive/channels/be/raw/latest/sdk/dartsdk-linux-arm64-release.zip" > "${HOME}/dartsdk.zip"
            unzip -o "${HOME}/dartsdk.zip" -d "${HOME}" > /dev/null
            if [ $? -ne 0 ]; then
              echo -e "::error::Download failed! Please check passed arguments."
              exit 1
            fi
            ls -la ${HOME}
            rm "${HOME}/dartsdk.zip"
          dockerRunArgs: |
            --volume "${PWD}:/source"
            --volume "${HOME}/dart-sdk:/dart-sdk"
            --user "${{ env.RUNNER_UID }}:${{ env.RUNNER_GID }}"
          env: |
            BUILD_VERSION: "${{ env.BUILD_VERSION }}"
            BUILD_BRANCH: "${{ github.head_ref }}"
            PUB_CACHE: "${HOME}/.pub-cache"
          install: |
            echo "DART_HOME=/dart-sdk" >> ${HOME}/.bashrc
          run: |
            cd /source
            /dart-sdk/bin/dart --version
            echo PUB_CACHE=${PUB_CACHE}
            echo BUILD_VERSION=${BUILD_VERSION}
            echo BUILD_BRANCH=${BUILD_BRANCH}
            /dart-sdk/bin/dart create -t server-shelf myserver

      - name: Show some information
        run: |
          pwd
          ls -la
          git status
          git log -1
          git diff
          echo BUILD_VERSION=${{ env.BUILD_VERSION }}
          echo BUILD_BRANCH=${{ env.BUILD_BRANCH }}
