name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dart-arm64:
    name: "Check if Dart is ready for arm64"
    runs-on: "ubuntu-latest"
    container:
      image:
        arm64v8/dart
      options: --tty --platform linux/arm64
    env:
      BUILD_OS: "linux"
      BUILD_ARCH: "${{ matrix.arch }}"
    steps:
      - uses: actions/checkout@v3
      - name: Compute BUILD_VERSION
        run: echo "BUILD_VERSION=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable
          architecture: x64

      - name: Show BUILD_VERSION
        run: echo "BUILD_VERSION=${{ env.BUILD_VERSION }}"

      - name: Show Dart SDK version
        run: echo "Dart SDK version `dart --version`"
